### ISSUE TITLE
Can not save settings

### ISSUE THREAD

**Issue by stefanmf** [engram-design/AssetCount#4]
When changing the plug-in settings and saving, a message of "Plugin settings saved." is shown, but the settings are reverted back to default.

**Steps to reproduce**
1. Go to settings page (/admin/asset-count/settings)
2. Change a setting
3. Save

**Additional info**
- Plugin version: 1.0.2
- Craft version: Craft Solo 3.5.15.1
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/asset-count/releases/tag/1.0.3)
