### ISSUE TITLE
Show on frontend

### ISSUE THREAD

**Issue by anoukaveresch** [engram-design/AssetCount#5]
How can I get the view count show up on the frontend (in the template)?

**Comment by engram-design** [comment]
```
{% set file = craft.assets.id(1234).one() %}

{{ craft.assetCount.getCount(file) }}
```

**Comment by anoukaveresch** [comment]
Thanks! The code you've send me didn't work, but when I use only the ID of the asset, it works. 
Like this:

`{{ craft.assetCount.getCount(1234) }}`

**Comment by engram-design** [comment]
Ah, my mistake - yes you need to pass the ID of the asset, not the asset.
